#!/bin/bash

# Update package lists and upgrade existing packages
sudo apt update
sudo apt upgrade -y

# Install necessary packages
sudo apt install -y git cmake make python3-pip screen ocl-icd-opencl-dev

# Clone xnm repository
git clone https://github.com/KEZGOD/xnm.git
cd xnm

# Give execute permission to xnm-one-gpu
chmod +x xnm-one-gpu

# Enter the XENGPUMiner directory
cd XENGPUMiner/

# Prompt the user for the mining address
read -p "Enter your mining address: " mining_address

# Create a screen session named "miner" and run the Python miner script
screen -S miner -dm python3 miner.py --gpu=true --account="$mining_address"

# Run xengpuminer in the background
nohup ./xengpuminer -b 128 &> output.log &

echo "Setup completed. You can check the progress in 'output.log'."
