#!/bin/bash

git clone https://github.com/shanhaicoder/XENGPUMiner.git && cd XENGPUMiner/

sudo apt update
sudo apt upgrade -y

sudo apt update
sudo apt upgrade -y
sudo apt install nano

sudo apt install -y git
sudo apt install -y cmake
sudo apt install -y make
sudo apt install -y python3-pip
sudo apt install screen
sudo apt install -y ocl-icd-opencl-dev

pip3 install -U -r requirements.txt

chmod +x build.sh
./build.sh -cuda_arch sm_89
pip3 install -U -r requirements.txt

echo -e "ezgod.eth\nReplace "ezgod.eth" with your mining address. Use 'Ctrl + X' to save, enter 'Y' to agree" > address.txt

echo "Please edit the 'address.txt' file and replace 'ezgod.eth' with your mining address. Save the file when you're done."
nano address.txt

mining_address=$(head -n 1 address.txt 2>/dev/null)
screen -S miner -dm python3 miner.py --gpu=true --account="$mining_address"

nohup ./xengpuminer -b 128 &> output.log &

echo "Checking Instructions

Mining operations:
   - 'tail -f output.log'
   - To exit, press 'Ctrl+C'

Block status:
   - 'screen -ls'
   - 'screen -r [process_number]'
   - To exit, press 'Ctrl+A+D'

挖矿脚本已启动
